// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixed_expense.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFixedExpense = `-- name: CreateFixedExpense :one
INSERT INTO fixed_expense (budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, interval_months, anchor_date, frequency_unit, interval_weeks, day_of_week, end_date, total_payments, is_installment_plan)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months, anchor_date, frequency_unit, interval_weeks, day_of_week, end_date, total_payments, is_installment_plan
`

type CreateFixedExpenseParams struct {
	BudgetProfileID   uuid.UUID      `json:"budget_profile_id"`
	Name              string         `json:"name"`
	PlannedAmount     pgtype.Numeric `json:"planned_amount"`
	CategoryID        *int32         `json:"category_id"`
	PaymentMethodID   *uuid.UUID     `json:"payment_method_id"`
	DayOfMonth        int32          `json:"day_of_month"`
	IntervalMonths    int32          `json:"interval_months"`
	AnchorDate        pgtype.Date    `json:"anchor_date"`
	FrequencyUnit     int16          `json:"frequency_unit"`
	IntervalWeeks     int32          `json:"interval_weeks"`
	DayOfWeek         int16          `json:"day_of_week"`
	EndDate           pgtype.Date    `json:"end_date"`
	TotalPayments     *int32         `json:"total_payments"`
	IsInstallmentPlan bool           `json:"is_installment_plan"`
}

func (q *Queries) CreateFixedExpense(ctx context.Context, arg CreateFixedExpenseParams) (FixedExpense, error) {
	row := q.db.QueryRow(ctx, createFixedExpense,
		arg.BudgetProfileID,
		arg.Name,
		arg.PlannedAmount,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.DayOfMonth,
		arg.IntervalMonths,
		arg.AnchorDate,
		arg.FrequencyUnit,
		arg.IntervalWeeks,
		arg.DayOfWeek,
		arg.EndDate,
		arg.TotalPayments,
		arg.IsInstallmentPlan,
	)
	var i FixedExpense
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Name,
		&i.PlannedAmount,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.DayOfMonth,
		&i.IsActive,
		&i.CreatedAt,
		&i.IntervalMonths,
		&i.AnchorDate,
		&i.FrequencyUnit,
		&i.IntervalWeeks,
		&i.DayOfWeek,
		&i.EndDate,
		&i.TotalPayments,
		&i.IsInstallmentPlan,
	)
	return i, err
}

const deactivateFixedExpense = `-- name: DeactivateFixedExpense :exec
UPDATE fixed_expense
SET is_active = FALSE
WHERE id = $1::uuid
  AND budget_profile_id = $2::uuid
`

type DeactivateFixedExpenseParams struct {
	ID              uuid.UUID `json:"id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) DeactivateFixedExpense(ctx context.Context, arg DeactivateFixedExpenseParams) error {
	_, err := q.db.Exec(ctx, deactivateFixedExpense, arg.ID, arg.BudgetProfileID)
	return err
}

const deleteUnpaidTransactionByFixedExpense = `-- name: DeleteUnpaidTransactionByFixedExpense :exec
DELETE FROM transaction
WHERE fixed_expense_id = $1::uuid
  AND is_paid = FALSE
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $2::uuid
        AND is_archived = FALSE
  )
`

type DeleteUnpaidTransactionByFixedExpenseParams struct {
	FixedExpenseID  uuid.UUID `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) DeleteUnpaidTransactionByFixedExpense(ctx context.Context, arg DeleteUnpaidTransactionByFixedExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteUnpaidTransactionByFixedExpense, arg.FixedExpenseID, arg.BudgetProfileID)
	return err
}

const fixedExpenseHasTransactionInMonth = `-- name: FixedExpenseHasTransactionInMonth :one
SELECT EXISTS (
    SELECT 1 FROM transaction
    WHERE fixed_expense_id = $1::uuid
      AND date >= $2::date
      AND date < $3::date
) AS exists
`

type FixedExpenseHasTransactionInMonthParams struct {
	FixedExpenseID uuid.UUID   `json:"fixed_expense_id"`
	MonthStart     pgtype.Date `json:"month_start"`
	MonthEnd       pgtype.Date `json:"month_end"`
}

func (q *Queries) FixedExpenseHasTransactionInMonth(ctx context.Context, arg FixedExpenseHasTransactionInMonthParams) (bool, error) {
	row := q.db.QueryRow(ctx, fixedExpenseHasTransactionInMonth, arg.FixedExpenseID, arg.MonthStart, arg.MonthEnd)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const fixedExpenseHasTransactionOnDate = `-- name: FixedExpenseHasTransactionOnDate :one
SELECT EXISTS (
    SELECT 1 FROM transaction
    WHERE fixed_expense_id = $1::uuid
      AND date = $2::date
) AS exists
`

type FixedExpenseHasTransactionOnDateParams struct {
	FixedExpenseID uuid.UUID   `json:"fixed_expense_id"`
	TargetDate     pgtype.Date `json:"target_date"`
}

func (q *Queries) FixedExpenseHasTransactionOnDate(ctx context.Context, arg FixedExpenseHasTransactionOnDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, fixedExpenseHasTransactionOnDate, arg.FixedExpenseID, arg.TargetDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFixedExpense = `-- name: GetFixedExpense :one
SELECT id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months, anchor_date, frequency_unit, interval_weeks, day_of_week, end_date, total_payments, is_installment_plan
FROM fixed_expense
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFixedExpense(ctx context.Context, id uuid.UUID) (FixedExpense, error) {
	row := q.db.QueryRow(ctx, getFixedExpense, id)
	var i FixedExpense
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Name,
		&i.PlannedAmount,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.DayOfMonth,
		&i.IsActive,
		&i.CreatedAt,
		&i.IntervalMonths,
		&i.AnchorDate,
		&i.FrequencyUnit,
		&i.IntervalWeeks,
		&i.DayOfWeek,
		&i.EndDate,
		&i.TotalPayments,
		&i.IsInstallmentPlan,
	)
	return i, err
}

const getTransactionByFixedExpense = `-- name: GetTransactionByFixedExpense :one
SELECT id, name, amount, planned_amount, date, renewal_date,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
FROM transaction
WHERE fixed_expense_id = $1::uuid
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $2::uuid
        AND is_archived = FALSE
  )
ORDER BY is_paid, date DESC NULLS LAST
LIMIT 1
`

type GetTransactionByFixedExpenseParams struct {
	FixedExpenseID  uuid.UUID `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

// Reconciling an edited template needs to know whether the current period's
// bill exists at all, not whether it is unpaid. GetUnpaidTransactionByFixedExpense
// answers the narrower question, and UpdateFixedExpense used to read a miss from
// it as "this bill just became due" and spawn a second transaction — so editing a
// bill after marking it paid produced a duplicate (issue #62).
func (q *Queries) GetTransactionByFixedExpense(ctx context.Context, arg GetTransactionByFixedExpenseParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByFixedExpense, arg.FixedExpenseID, arg.BudgetProfileID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const getUnpaidTransactionByFixedExpense = `-- name: GetUnpaidTransactionByFixedExpense :one
SELECT id, name, amount, planned_amount, date, renewal_date,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
FROM transaction
WHERE fixed_expense_id = $1::uuid
  AND is_paid = FALSE
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $2::uuid
        AND is_archived = FALSE
  )
ORDER BY date DESC NULLS LAST
LIMIT 1
`

type GetUnpaidTransactionByFixedExpenseParams struct {
	FixedExpenseID  uuid.UUID `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID `json:"budget_profile_id"`
}

func (q *Queries) GetUnpaidTransactionByFixedExpense(ctx context.Context, arg GetUnpaidTransactionByFixedExpenseParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getUnpaidTransactionByFixedExpense, arg.FixedExpenseID, arg.BudgetProfileID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const getUnpaidTransactionByFixedExpenseInPeriod = `-- name: GetUnpaidTransactionByFixedExpenseInPeriod :one
SELECT id, name, amount, planned_amount, date, renewal_date,
       budget_period_id, category_id, payment_method_id, transaction_frequency_id, transaction_type_id,
       is_paid, paid_date, fixed_expense_id, plaid_transaction_id, is_excluded, installment_fixed_expense_id, carried_from_budget_period_id,
       plaid_pfc_primary, plaid_pfc_detailed, plaid_reference_number, plaid_ppd_id
FROM transaction
WHERE fixed_expense_id = $1::uuid
  AND is_paid = FALSE
  AND budget_period_id = $2::uuid
ORDER BY date DESC NULLS LAST
LIMIT 1
`

type GetUnpaidTransactionByFixedExpenseInPeriodParams struct {
	FixedExpenseID uuid.UUID `json:"fixed_expense_id"`
	BudgetPeriodID uuid.UUID `json:"budget_period_id"`
}

// Same as above but scoped to one period. Used by every auto-match path: a
// payment may only settle the bill for the period it actually falls in.
// GetUnpaidTransactionByFixedExpense searches every live period newest-first,
// so a transaction imported into a closed period would reach forward and mark
// the *next* period's bill paid (see issue #41).
func (q *Queries) GetUnpaidTransactionByFixedExpenseInPeriod(ctx context.Context, arg GetUnpaidTransactionByFixedExpenseInPeriodParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getUnpaidTransactionByFixedExpenseInPeriod, arg.FixedExpenseID, arg.BudgetPeriodID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.PlannedAmount,
		&i.Date,
		&i.RenewalDate,
		&i.BudgetPeriodID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.TransactionFrequencyID,
		&i.TransactionTypeID,
		&i.IsPaid,
		&i.PaidDate,
		&i.FixedExpenseID,
		&i.PlaidTransactionID,
		&i.IsExcluded,
		&i.InstallmentFixedExpenseID,
		&i.CarriedFromBudgetPeriodID,
		&i.PlaidPfcPrimary,
		&i.PlaidPfcDetailed,
		&i.PlaidReferenceNumber,
		&i.PlaidPpdID,
	)
	return i, err
}

const listFixedExpenses = `-- name: ListFixedExpenses :many
SELECT id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months, anchor_date, frequency_unit, interval_weeks, day_of_week, end_date, total_payments, is_installment_plan
FROM fixed_expense
WHERE budget_profile_id = $1 AND is_active = TRUE
ORDER BY name
`

func (q *Queries) ListFixedExpenses(ctx context.Context, budgetProfileID uuid.UUID) ([]FixedExpense, error) {
	rows, err := q.db.Query(ctx, listFixedExpenses, budgetProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FixedExpense
	for rows.Next() {
		var i FixedExpense
		if err := rows.Scan(
			&i.ID,
			&i.BudgetProfileID,
			&i.Name,
			&i.PlannedAmount,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.DayOfMonth,
			&i.IsActive,
			&i.CreatedAt,
			&i.IntervalMonths,
			&i.AnchorDate,
			&i.FrequencyUnit,
			&i.IntervalWeeks,
			&i.DayOfWeek,
			&i.EndDate,
			&i.TotalPayments,
			&i.IsInstallmentPlan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFixedExpense = `-- name: UpdateFixedExpense :one
UPDATE fixed_expense
SET name              = $1,
    planned_amount    = $2,
    category_id       = $3,
    payment_method_id = $4,
    day_of_month      = $5,
    interval_months   = $6,
    anchor_date       = $7,
    frequency_unit    = $8,
    interval_weeks    = $9,
    day_of_week       = $10,
    end_date          = $11,
    total_payments    = $12
WHERE id = $13::uuid
  AND budget_profile_id = $14::uuid
RETURNING id, budget_profile_id, name, planned_amount, category_id, payment_method_id, day_of_month, is_active, created_at, interval_months, anchor_date, frequency_unit, interval_weeks, day_of_week, end_date, total_payments, is_installment_plan
`

type UpdateFixedExpenseParams struct {
	Name            string         `json:"name"`
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
	CategoryID      *int32         `json:"category_id"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	DayOfMonth      int32          `json:"day_of_month"`
	IntervalMonths  int32          `json:"interval_months"`
	AnchorDate      pgtype.Date    `json:"anchor_date"`
	FrequencyUnit   int16          `json:"frequency_unit"`
	IntervalWeeks   int32          `json:"interval_weeks"`
	DayOfWeek       int16          `json:"day_of_week"`
	EndDate         pgtype.Date    `json:"end_date"`
	TotalPayments   *int32         `json:"total_payments"`
	ID              uuid.UUID      `json:"id"`
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
}

func (q *Queries) UpdateFixedExpense(ctx context.Context, arg UpdateFixedExpenseParams) (FixedExpense, error) {
	row := q.db.QueryRow(ctx, updateFixedExpense,
		arg.Name,
		arg.PlannedAmount,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.DayOfMonth,
		arg.IntervalMonths,
		arg.AnchorDate,
		arg.FrequencyUnit,
		arg.IntervalWeeks,
		arg.DayOfWeek,
		arg.EndDate,
		arg.TotalPayments,
		arg.ID,
		arg.BudgetProfileID,
	)
	var i FixedExpense
	err := row.Scan(
		&i.ID,
		&i.BudgetProfileID,
		&i.Name,
		&i.PlannedAmount,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.DayOfMonth,
		&i.IsActive,
		&i.CreatedAt,
		&i.IntervalMonths,
		&i.AnchorDate,
		&i.FrequencyUnit,
		&i.IntervalWeeks,
		&i.DayOfWeek,
		&i.EndDate,
		&i.TotalPayments,
		&i.IsInstallmentPlan,
	)
	return i, err
}

const updateFixedExpenseFromPayment = `-- name: UpdateFixedExpenseFromPayment :exec
UPDATE fixed_expense
SET planned_amount    = $1,
    day_of_month      = $2,
    day_of_week       = $3,
    anchor_date       = $4,
    category_id       = $5,
    payment_method_id = $6
WHERE id = $7::uuid
`

type UpdateFixedExpenseFromPaymentParams struct {
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
	DayOfMonth      int32          `json:"day_of_month"`
	DayOfWeek       int16          `json:"day_of_week"`
	AnchorDate      pgtype.Date    `json:"anchor_date"`
	CategoryID      *int32         `json:"category_id"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	ID              uuid.UUID      `json:"id"`
}

// Brings the template up to what actually happened when a bill was paid:
// amount, due date (day_of_month/day_of_week/anchor_date, all derived
// together from the same real paid date), category, and payment method. See
// docs/features/planned-amount-follows-paid.md for which fields the caller
// is expected to leave unchanged when it has no better value (category_id/
// payment_method_id keep the template's own when nothing was observed).
func (q *Queries) UpdateFixedExpenseFromPayment(ctx context.Context, arg UpdateFixedExpenseFromPaymentParams) error {
	_, err := q.db.Exec(ctx, updateFixedExpenseFromPayment,
		arg.PlannedAmount,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.AnchorDate,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.ID,
	)
	return err
}

const updatePaidTransactionFromFixedExpense = `-- name: UpdatePaidTransactionFromFixedExpense :exec
UPDATE transaction
SET name              = $1,
    category_id       = $2,
    payment_method_id = $3
WHERE fixed_expense_id = $4::uuid
  AND is_paid = TRUE
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $5::uuid
        AND is_archived = FALSE
  )
`

type UpdatePaidTransactionFromFixedExpenseParams struct {
	Name            *string    `json:"name"`
	CategoryID      *int32     `json:"category_id"`
	PaymentMethodID *uuid.UUID `json:"payment_method_id"`
	FixedExpenseID  uuid.UUID  `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID  `json:"budget_profile_id"`
}

// Propagate a template edit onto an already-paid transaction.
//
// Deliberately narrower than UpdateTransactionFromFixedExpense: `amount` is what
// the user actually paid and `planned_amount` is what this period was planned at,
// and neither is the template's business once the bill is settled. Only future
// periods follow the template's amount — the same rule
// docs/features/planned-amount-follows-paid.md already sets for the reverse
// direction. is_paid/paid_date are untouched for the same reason: editing a
// bill's category must never quietly un-pay it.
func (q *Queries) UpdatePaidTransactionFromFixedExpense(ctx context.Context, arg UpdatePaidTransactionFromFixedExpenseParams) error {
	_, err := q.db.Exec(ctx, updatePaidTransactionFromFixedExpense,
		arg.Name,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.FixedExpenseID,
		arg.BudgetProfileID,
	)
	return err
}

const updateTransactionFromFixedExpense = `-- name: UpdateTransactionFromFixedExpense :exec
UPDATE transaction
SET name              = $1,
    planned_amount    = $2,
    amount            = $2,
    category_id       = $3,
    payment_method_id = $4,
    date              = $5
WHERE fixed_expense_id = $6::uuid
  AND is_paid = FALSE
  AND budget_period_id IN (
      SELECT id FROM budget_period
      WHERE budget_profile_id = $7::uuid
        AND is_archived = FALSE
  )
`

type UpdateTransactionFromFixedExpenseParams struct {
	Name            *string        `json:"name"`
	PlannedAmount   pgtype.Numeric `json:"planned_amount"`
	CategoryID      *int32         `json:"category_id"`
	PaymentMethodID *uuid.UUID     `json:"payment_method_id"`
	Date            pgtype.Date    `json:"date"`
	FixedExpenseID  uuid.UUID      `json:"fixed_expense_id"`
	BudgetProfileID uuid.UUID      `json:"budget_profile_id"`
}

func (q *Queries) UpdateTransactionFromFixedExpense(ctx context.Context, arg UpdateTransactionFromFixedExpenseParams) error {
	_, err := q.db.Exec(ctx, updateTransactionFromFixedExpense,
		arg.Name,
		arg.PlannedAmount,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Date,
		arg.FixedExpenseID,
		arg.BudgetProfileID,
	)
	return err
}
